In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.cluster import DBSCAN
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
df = pd.read_csv('updated df 05-20-2020.csv')

In [4]:
df.fillna(0, inplace=True)

In [5]:
X = df.drop(columns=['Player', 'Pos', 'Team', 'Year', 'Age'])

In [6]:
ss = StandardScaler()

In [7]:
X_scaled = ss.fit_transform(X)

In [8]:
db_model = DBSCAN(eps=4.1, min_samples=4)
db_model.fit(X_scaled)

DBSCAN(algorithm='auto', eps=4.1, leaf_size=30, metric='euclidean',
       metric_params=None, min_samples=4, n_jobs=None, p=None)

### Only creating noise cluster?

In [9]:
set(db_model.labels_)

{-1, 0, 1, 2, 3, 4}

In [10]:
silhouette_score(X_scaled, db_model.labels_)

0.05149207009218736

In [11]:
df['cluster'] = db_model.labels_

In [12]:
df.head(3)

         Player Pos  Age Team  Games  GS    MP   FG  FGA    FG%   3P  3PA    3P%   2P  2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  PTS  Year   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  cluster
0   Carl Landry  PF   32  PHI     36  12  15.8  3.9  6.9  0.556  0.2  0.4  0.462  3.7  6.6  0.561  0.568  1.9  2.5  0.736  1.4  2.7  4.1  0.9  0.3  0.3  0.6  1.9  9.8  2016  22.4  0.605  0.052  0.364   9.1  19.2  14.0  11.1   1.0   1.2   7.1  24.0  1.8  0.3  2.1  0.176   2.6  -1.4  1.2   0.5       -1
1     O.J. Mayo  SG   28  MIL     41  24  26.6  2.9  7.8  0.371  1.3  4.0  0.321  1.6  3.9  0.421  0.452  0.8  1.0  0.775  0.3  2.2  2.6  2.9  1.2  0.2  1.8  3.1  7.8  2016   7.7  0.474  0.505  0.125   1.4   9.6   5.5  15.8   2.2   0.6  17.5  17.0 -0.7  0.6 -0.1 -0.005  -3.8  -0.2 -4.0  -0.6        0
2  Ray McCallum  PG   24  MEM     10   3  21.9  2.8  7.9  0.354  1.0  2.6  0.385  1.8  5.3  0.340  0.418  0.3  0.5  0.600  0.2  1.4  1.6  2.7  0.7  0.3  1.3  1.5  6.9  2016   9.1  0.449  0.288  0.103   1.9   9.3   5.6  18.5   1.3   1.2  13.6  16.8 -0.2  0.5  0.3  0.034  -2.6  -0.5 -3.1  -0.1        0

In [13]:
df['cluster'].value_counts(normalize=True)

 0    0.685990
-1    0.270531
 4    0.014493
 1    0.012077
 3    0.009662
 2    0.007246
Name: cluster, dtype: float64

In [14]:
df.groupby('cluster').mean()

               Age      Games         GS         MP        FG        FGA       FG%        3P       3PA       3P%        2P        2PA       2P%      eFG%        FT       FTA       FT%       ORB       DRB       TRB       AST       STL       BLK       TOV        PF        PTS         Year        PER       TS%      3PAr       FTr       ORB%       DRB%       TRB%       AST%      STL%      BLK%       TOV%       USG%       OWS       DWS        WS     WS/48      OBPM      DBPM       BPM      VORP
cluster
-1       26.464286  47.616071  38.758929  27.448214  5.404464  11.222321  0.485107  1.040179  3.018750  0.257232  4.363393   8.200893  0.523116  0.527089  2.691964  3.589286  0.682277  1.645536  4.817857  6.458036  3.109821  0.922321  0.811607  1.882143  2.479464  14.537500  2018.616071  17.525000  0.560402  0.253571  0.321625   6.608929  18.725000  12.687500  16.635714  1.576786  2.506250  12.955357  22.051786  2.666071  1.953571  4.612500  0.118321  0.701786  0.198214  0.890179  1.756250
 0       26.911972  54.809859  25.348592  23.013380  3.392254   7.841197  0.431176  1.146479  3.258803  0.339768  2.248592   4.585915  0.491049  0.504849  1.280282  1.674648  0.761338  0.713028  2.790845  3.496479  2.228873  0.705986  0.345775  1.148239  1.920423   9.217606  2018.690141  12.047535  0.535342  0.423194  0.213968   3.349648  13.007394   8.161972  13.876761  1.466901  1.284155  12.017958  17.814085  0.984507  1.232746  2.220070  0.068243 -1.337324 -0.269718 -1.604225  0.278873
 1       26.400000  40.800000  10.400000  17.120000  3.020000   5.600000  0.543000  0.000000  0.000000  0.000000  3.020000   5.580000  0.543600  0.543000  1.660000  2.660000  0.633600  1.680000  3.920000  5.620000  1.200000  0.480000  0.880000  0.980000  2.280000   7.720000  2017.800000  18.540000  0.579000  0.002200  0.513400  11.000000  24.060000  17.560000  10.420000  1.300000  4.240000  12.660000  19.800000  1.540000  1.080000  2.640000  0.146000 -0.420000  0.620000  0.200000  0.480000
 2       26.000000  78.666667  19.333333  17.900000  2.733333   4.466667  0.620000  0.000000  0.033333  0.033333  2.733333   4.433333  0.625333  0.620667  0.800000  1.300000  0.620000  2.200000  3.166667  5.366667  1.433333  0.466667  0.700000  0.733333  1.933333   6.366667  2018.333333  18.400000  0.629667  0.009667  0.296333  13.900000  19.000000  16.500000  11.300000  1.233333  3.233333  13.033333  14.266667  3.633333  1.966667  5.600000  0.191000  0.700000  0.733333  1.433333  1.200000
 3       25.500000  47.250000  23.000000  16.400000  2.875000   5.075000  0.565500  0.000000  0.050000  0.050000  2.875000   5.050000  0.569500  0.565750  1.100000  1.675000  0.665000  1.650000  3.275000  4.950000  0.875000  0.225000  0.475000  0.925000  2.025000   6.875000  2019.000000  15.500000  0.588500  0.008000  0.334750  10.800000  21.150000  15.975000   7.725000  0.675000  2.325000  13.850000  17.225000  1.100000  0.550000  1.650000  0.106500 -1.350000 -0.925000 -2.300000 -0.050000
 4       27.666667  74.666667  74.666667  34.950000  8.483333  18.516667  0.458333  2.550000  7.033333  0.361000  5.950000  11.483333  0.516000  0.526667  4.350000  5.150000  0.841667  0.900000  3.683333  4.566667  6.550000  1.366667  0.516667  2.600000  2.133333  23.850000  2019.000000  21.883333  0.573833  0.377667  0.279000   2.700000  11.350000   7.033333  30.716667  1.900000  1.283333  11.066667  28.583333  6.083333  2.183333  8.266667  0.152833  4.883333 -0.166667  4.733333  4.366667

### DBSCAN is not great, Hierarchical Clustering Next! (Agglomerative Clustering)

In [15]:
from sklearn.cluster import AgglomerativeClustering
ac = AgglomerativeClustering(n_clusters=8, affinity='euclidean', linkage='ward')  
model_ac = ac.fit(X_scaled)

In [16]:
model_ac.labels_

array([2, 3, 0, 3, 2, 3, 0, 0, 1, 3, 3, 0, 6, 0, 5, 3, 5, 3, 1, 1, 2, 0,
       1, 3, 3, 0, 0, 3, 0, 3, 3, 1, 0, 0, 3, 3, 2, 2, 3, 3, 3, 0, 2, 2,
       6, 0, 0, 2, 3, 0, 2, 0, 6, 0, 5, 0, 5, 3, 0, 0, 3, 3, 0, 0, 2, 3,
       0, 0, 3, 0, 0, 3, 0, 3, 5, 7, 2, 2, 6, 1, 0, 5, 2, 3, 2, 2, 3, 5,
       2, 2, 3, 2, 2, 1, 3, 3, 5, 4, 6, 5, 3, 5, 2, 5, 5, 2, 6, 3, 1, 0,
       0, 0, 2, 2, 3, 5, 5, 7, 2, 3, 5, 2, 0, 3, 3, 1, 3, 1, 2, 2, 2, 3,
       2, 1, 7, 2, 5, 3, 3, 3, 5, 7, 3, 0, 1, 6, 1, 5, 5, 0, 5, 5, 1, 2,
       4, 3, 6, 0, 3, 4, 3, 6, 6, 4, 3, 0, 5, 2, 3, 5, 2, 2, 3, 5, 1, 5,
       6, 7, 1, 1, 1, 6, 5, 7, 7, 2, 5, 7, 3, 1, 5, 1, 2, 2, 4, 5, 5, 3,
       2, 1, 3, 5, 2, 2, 3, 3, 3, 6, 1, 5, 5, 1, 3, 7, 4, 3, 6, 7, 3, 0,
       3, 2, 3, 6, 5, 2, 3, 5, 2, 3, 5, 2, 2, 4, 4, 4, 2, 2, 1, 3, 6, 1,
       3, 3, 3, 1, 2, 2, 2, 5, 2, 3, 2, 2, 2, 7, 4, 6, 2, 1, 0, 3, 2, 3,
       5, 4, 2, 2, 7, 2, 5, 5, 5, 2, 0, 2, 2, 3, 2, 5, 1, 3, 3, 2, 3, 1,
       4, 0, 4, 6, 4, 1, 3, 6, 6, 0, 2, 2, 0, 7, 2, 6, 2, 5, 0, 3, 5, 5,
       0, 6, 0, 2, 3, 7, 2, 2, 3, 0, 2, 6, 6, 5, 3, 2, 7, 3, 5, 3, 0, 7,
       2, 3, 1, 2, 6, 7, 6, 4, 3, 2, 5, 3, 2, 5, 2, 6, 2, 2, 7, 3, 3, 5,
       1, 2, 2, 0, 1, 6, 2, 5, 5, 7, 6, 0, 3, 6, 3, 2, 5, 4, 2, 3, 3, 1,
       1, 2, 2, 5, 0, 7, 3, 5, 2, 3, 7, 2, 2, 5, 4, 5, 5, 1, 0, 6, 3, 3,
       5, 6, 2, 2, 2, 7, 1, 7, 5, 7, 3, 3, 5, 2, 0, 6, 5, 1], dtype=int64)

In [17]:
df['cluster'] = model_ac.labels_

In [18]:
df['cluster'].value_counts()

3    94
2    94
5    62
0    52
1    38
6    33
7    24
4    17
Name: cluster, dtype: int64

In [19]:
df.groupby('cluster').mean()

               Age      Games         GS         MP        FG        FGA       FG%        3P       3PA       3P%        2P        2PA       2P%      eFG%        FT       FTA       FT%       ORB       DRB        TRB       AST       STL       BLK       TOV        PF        PTS         Year        PER       TS%      3PAr       FTr       ORB%       DRB%       TRB%       AST%      STL%      BLK%       TOV%       USG%       OWS       DWS        WS     WS/48      OBPM      DBPM       BPM      VORP
cluster
0        27.038462  26.269231   7.692308  18.896154  2.036538   5.592308  0.375135  0.732692  2.459615  0.270615  1.305769   3.134615  0.428654  0.439981  0.607692  0.907692  0.619538  0.484615  1.909615   2.380769  1.446154  0.532692  0.219231  0.853846  1.750000   5.413462  2018.134615   7.300000  0.466135  0.433500  0.168442   2.869231  11.503846   7.138462  11.005769  1.355769  1.015385  12.225000  15.725000 -0.125000  0.409615  0.284615  0.002269 -3.884615 -0.809615 -4.700000 -0.263462
1        26.368421  51.289474  26.842105  21.050000  3.797368   6.686842  0.576763  0.115789  0.397368  0.107263  3.689474   6.289474  0.592763  0.583553  1.657895  2.505263  0.648947  2.400000  4.400000   6.794737  1.189474  0.484211  1.044737  1.126316  2.486842   9.368421  2018.657895  18.321053  0.604500  0.049789  0.412842  12.160526  22.423684  17.289474   8.323684  1.068421  4.034211  12.850000  17.852632  2.342105  1.460526  3.794737  0.148158 -0.081579  0.113158  0.028947  0.736842
2        26.819149  52.946809  16.808511  22.303191  3.162766   7.268085  0.437755  1.371277  3.764894  0.358777  1.786170   3.506383  0.512309  0.531011  1.031915  1.361702  0.762447  0.743617  2.760638   3.493617  1.480851  0.596809  0.359574  0.854255  1.904255   8.736170  2018.787234  12.010638  0.555628  0.512468  0.198287   3.822340  13.478723   8.655319   9.271277  1.271277  1.471277  10.028723  16.591489  1.089362  1.203191  2.291489  0.084021 -0.990426 -0.252128 -1.243617  0.214894
3        26.872340  50.202128  17.031915  21.595745  3.006383   7.173404  0.419628  0.828723  2.481915  0.321947  2.181915   4.698936  0.467074  0.478819  1.252128  1.650000  0.755394  0.518085  2.329787   2.844681  3.026596  0.793617  0.248936  1.354255  1.832979   8.105319  2018.489362  11.694681  0.515394  0.357521  0.229457   2.507447  11.526596   7.003191  20.062766  1.758511  0.948936  14.775532  18.426596  0.360638  0.939362  1.304255  0.051266 -1.990426 -0.239362 -2.219149 -0.015957
4        24.823529  70.470588  60.176471  31.035294  7.641176  13.988235  0.554824  0.535294  1.670588  0.241529  7.094118  12.305882  0.580353  0.571588  4.088235  5.558824  0.728000  3.241176  7.841176  11.094118  3.070588  0.941176  1.347059  2.335294  3.005882  19.911765  2019.000000  24.382353  0.609353  0.105529  0.406176  11.152941  26.805882  19.035294  16.076471  1.447059  3.576471  12.400000  25.488235  5.800000  3.535294  9.347059  0.200529  3.435294  0.994118  4.405882  3.635294
5        26.983871  59.854839  48.387097  30.151613  5.932258  13.238710  0.449419  1.827419  4.972581  0.364097  4.114516   8.267742  0.498210  0.519694  2.677419  3.312903  0.811468  0.890323  4.064516   4.943548  3.241935  0.927419  0.450000  1.782258  2.183871  16.361290  2018.870968  16.148387  0.558435  0.380565  0.249161   3.179032  14.540323   8.862903  16.424194  1.472581  1.238710  10.864516  23.398387  2.093548  1.727419  3.819355  0.097371  0.951613 -0.530645  0.419355  1.112903
6        27.393939  70.787879  55.969697  27.124242  3.766667   7.778788  0.483303  0.927273  2.596970  0.332455  2.842424   5.178788  0.545939  0.543273  1.445455  1.969697  0.725939  1.396970  4.542424   5.939394  2.451515  1.036364  0.890909  1.287879  2.503030   9.918182  2018.848485  14.866667  0.570242  0.338939  0.255606   5.624242  18.257576  11.945455  12.757576  1.842424  2.812121  13.106061  15.951515  2.330303  2.678788  5.012121  0.121636 -0.300000  1.384848  1.072727  1.533333
7        26.291667  71.666667  71.625000  34.312500  8.429167  18.287500  0.462917  2.295833  6.395833  0.332625  6.133333  11.883333  0.515292  0.523625  4.741667  5.916667  0.799042  0.933333  4.845833   5.783333  6.508333  1.341667  0.504167  3.158333  2.304167  23.895833  2019.000000  21.462500  0.570708  0.339083  0.325625   2.875000  15.033333   8.958333  31.116667  1.870833  1.220833  13.158333  29.708333  4.733333  2.570833  7.300000  0.139750  4.187500  0.020833  4.212500  3.895833

### Cluster 0 NAME: Bench Players

In [20]:
df[df['cluster'] == 0].head(2)

         Player Pos  Age Team  Games  GS    MP   FG  FGA    FG%   3P  3PA    3P%   2P  2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  PTS  Year  PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM   BPM  VORP  cluster
2  Ray McCallum  PG   24  MEM     10   3  21.9  2.8  7.9  0.354  1.0  2.6  0.385  1.8  5.3  0.340  0.418  0.3  0.5  0.600  0.2  1.4  1.6  2.7  0.7  0.3  1.3  1.5  6.9  2016  9.1  0.449  0.288  0.103   1.9   9.3   5.6  18.5   1.3   1.2  13.6  16.8 -0.2  0.5  0.3  0.034  -2.6  -0.5  -3.1  -0.1        0
6   Tony Wroten  PG   22  PHI      8   3  18.0  2.8  8.1  0.338  0.4  2.1  0.176  2.4  6.0  0.396  0.362  2.5  4.6  0.541  0.3  2.4  2.6  2.5  0.4  0.0  3.6  1.4  8.4  2016  1.8  0.412  0.262  0.569   1.5  14.9   7.9  23.3   1.0   0.0  26.3  33.5 -0.8  0.0 -0.8 -0.263  -8.4  -5.0 -13.4  -0.4        0

### Cluster 1 NAME: Defensive Big Men

In [21]:
df[df['cluster'] == 1].head(2)

            Player Pos  Age Team  Games  GS    MP   FG  FGA    FG%   3P  3PA  3P%   2P  2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  PTS  Year   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  cluster
8   Alex Stepheson  PF   28  MEM      4   0  15.3  2.0  6.5  0.308  0.0  0.0  0.0  2.0  6.5  0.308  0.308  1.0  2.5  0.400  4.5  2.0  6.5  0.5  0.3  0.8  0.0  2.0  5.0  2016  14.8  0.341  0.000  0.444  28.5  14.5  21.8   4.3   0.7   6.0   0.0  19.8  0.0  0.1  0.1  0.068  -0.5  -2.0 -2.4   0.0        1
18    J.J. Hickson   C   27  DEN     20   9  15.3  2.8  5.5  0.505  0.0  0.0  0.0  2.8  5.5  0.505  0.505  1.4  3.0  0.458  1.1  3.3  4.4  0.8  0.5  0.6  0.8  1.8  6.9  2016  16.8  0.514  0.006  0.665   9.8  24.1  16.8   8.7   1.7   2.6  11.1  22.6  0.3  0.5  0.8  0.088  -1.1   0.0 -1.1   0.1        1

### Cluster 2 Off the bench Wing Role Players, shooters/defense, avg 3pa(3.76) per game, not many assists at all.. NAME: 3 and D Wings, 2-way Wings,

In [22]:
df[df['cluster'] == 2].head(2)

           Player Pos  Age Team  Games  GS    MP   FG  FGA    FG%   3P  3PA    3P%   2P  2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  PTS  Year   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  cluster
0     Carl Landry  PF   32  PHI     36  12  15.8  3.9  6.9  0.556  0.2  0.4  0.462  3.7  6.6  0.561  0.568  1.9  2.5  0.736  1.4  2.7  4.1  0.9  0.3  0.3  0.6  1.9  9.8  2016  22.4  0.605  0.052  0.364   9.1  19.2  14.0  11.1   1.0   1.2   7.1  24.0  1.8  0.3  2.1  0.176   2.6  -1.4  1.2   0.5        2
4  Jason Thompson   C   29  TOR     19   6  15.4  1.7  3.5  0.485  0.3  0.8  0.333  1.4  2.7  0.529  0.523  0.9  1.2  0.818  1.2  3.1  4.2  0.5  0.4  0.6  0.4  2.1  4.6  2016  14.2  0.558  0.139  0.500   7.9  23.4  15.9   8.5   1.3   3.3  10.2  13.9  0.9  0.7  1.6  0.165  -2.1   1.2 -0.8   0.1        2

### Cluster 3 (all PG, SG) all off the bench Guards.. maybe Secondary floor generals?

In [23]:
df[df['cluster'] == 3].head(2)

         Player Pos  Age Team  Games  GS    MP   FG  FGA    FG%   3P  3PA    3P%   2P  2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  PTS  Year   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  cluster
1     O.J. Mayo  SG   28  MIL     41  24  26.6  2.9  7.8  0.371  1.3  4.0  0.321  1.6  3.9  0.421  0.452  0.8  1.0  0.775  0.3  2.2  2.6  2.9  1.2  0.2  1.8  3.1  7.8  2016   7.7  0.474  0.505  0.125   1.4   9.6   5.5  15.8   2.2   0.6  17.5  17.0 -0.7  0.6 -0.1 -0.005  -3.8  -0.2 -4.0  -0.6        3
3  Kevin Martin  SG   32  TOT     55  13  19.9  2.8  7.6  0.372  0.9  2.5  0.360  1.9  5.1  0.378  0.431  2.8  3.1  0.890  0.3  1.7  2.0  1.1  0.5  0.1  1.0  1.5  9.3  2016  11.5  0.520  0.325  0.411   1.5  10.0   5.8   8.2   1.2   0.2   9.8  22.6  0.7  0.5  1.2  0.054  -1.6  -1.6 -3.2  -0.4        3

### Cluster 4 , Elite high efficiency centers fg% (0.5548), All-Stars, 2PA(12.31) most of all clusters, reb(11.09) most of all clusters, OWS(5.8) highest, + - (4.41) 

#### NAME: Elite Overall Centers?

In [24]:
df[df['cluster'] == 4].head(2)

                 Player Pos  Age Team  Games  GS    MP   FG   FGA    FG%   3P  3PA    3P%   2P   2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS  Year   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS    WS  WS/48  OBPM  DBPM  BPM  VORP  cluster
97         Jusuf Nurkić   C   24  POR     72  72  27.4  5.8  11.5  0.508  0.0  0.4  0.103  5.8  11.1  0.523  0.510  3.9  5.1  0.773  3.4  7.0  10.4  3.2  1.0  1.4  2.3  3.5  15.6  2019  23.4  0.570  0.035  0.442  13.4  26.7  20.2  17.9   1.7   4.2  14.6  24.7  4.4  3.3   7.8  0.189   2.1   1.7  3.7   2.8        4
154  Karl-Anthony Towns   C   23  MIN     77  77  33.1  8.8  17.1  0.518  1.8  4.6  0.400  7.0  12.5  0.562  0.572  4.9  5.8  0.836  3.4  9.0  12.4  3.4  0.9  1.6  3.1  3.8  24.4  2019  26.3  0.622  0.270  0.342  10.9  29.3  20.0  17.2   1.3   4.2  13.7  28.9  7.2  3.2  10.4  0.197   5.4   0.6  6.0   5.1        4

### Cluster 5 two way guards/forwards, efficient shooters, average 3p% (0.364) _highest of all clusters_


#### NAME: Shooting Specialists?

In [25]:
df[df['cluster'] == 5].head(2)

          Player Pos  Age Team  Games  GS    MP   FG   FGA    FG%   3P  3PA    3P%   2P   2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS  Year   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  cluster
14  Kobe Bryant*  SF   37  LAL     66  66  28.2  6.0  16.9  0.358  2.0  7.1  0.285  4.0   9.8  0.410  0.417  3.5  4.3  0.826  0.6  3.1  3.7  2.8  0.9  0.2  2.0  1.7  17.6  2016  14.9  0.469  0.420  0.252   2.3  12.3   7.1  19.1   1.7   0.5   9.4  32.2 -0.9  0.5 -0.4 -0.010   0.9  -2.4 -1.6   0.2        5
16    Chris Bosh  PF   31  MIA     53  53  33.5  6.8  14.5  0.467  1.5  4.2  0.365  5.2  10.3  0.508  0.520  4.0  5.1  0.795  0.9  6.5  7.4  2.4  0.7  0.6  1.5  1.9  19.1  2016  20.2  0.571  0.289  0.349   3.2  21.1  12.4  12.1   1.0   1.5   8.1  24.7  4.1  2.3  6.4  0.172   3.6   0.5  4.0   2.7        5

### Cluster 6 Defensive Specialists

In [26]:
df[df['cluster'] == 6].head(2)

             Player Pos  Age Team  Games  GS    MP   FG  FGA    FG%   3P  3PA    3P%   2P  2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  PTS  Year   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  cluster
12      Tim Duncan*   C   39  SAS     61  60  25.2  3.5  7.2  0.488  0.0  0.0  0.000  3.5  7.2  0.490  0.488  1.5  2.1  0.702  1.9  5.4  7.3  2.7  0.8  1.3  1.5  2.0  8.6  2016  16.9  0.523  0.005  0.297   8.8  23.8  16.6  15.3   1.6   3.9  15.3  17.6  1.6  3.6  5.2  0.163  -0.1   3.1  3.0   2.0        6
44  Dejounte Murray  PG   21  SAS     81  48  21.5  3.3  7.5  0.443  0.1  0.4  0.265  3.2  7.1  0.454  0.451  1.3  1.8  0.709  1.4  4.3  5.7  2.9  1.2  0.4  1.7  1.9  8.1  2018  15.1  0.485  0.056  0.243   7.0  22.4  14.6  20.2   2.8   1.5  16.6  20.7 -0.2  3.4  3.2  0.087  -1.6   2.2  0.5   1.1        6

### Cluster 7 


#### NAMES: Elite Overall Guards?

In [27]:
df[df['cluster'] == 7].head(2)

               Player Pos  Age Team  Games  GS    MP   FG   FGA    FG%   3P  3PA    3P%   2P   2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS  Year   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP  cluster
75   Donovan Mitchell  SG   22  UTA     77  77  33.7  8.6  19.9  0.432  2.4  6.7  0.362  6.1  13.1  0.468  0.493  4.1  5.1  0.806  0.8  3.3  4.1  4.2  1.4  0.4  2.8  2.7  23.8  2019  17.2  0.537  0.339  0.259   2.5  10.5   6.6  21.2   2.0   0.9  11.3  31.6  1.3  3.7  5.0  0.092   1.2   0.1  1.3   2.2        7
117       Zach LaVine  SG   23  CHI     63  62  34.5  8.4  18.0  0.467  1.9  5.1  0.374  6.5  12.9  0.504  0.520  5.0  6.0  0.832  0.6  4.0  4.7  4.5  1.0  0.4  3.4  2.2  23.7  2019  18.7  0.574  0.283  0.330   2.0  12.9   7.4  22.6   1.3   1.0  14.2  30.5  1.7  1.1  2.8  0.062   2.4  -1.6  0.8   1.5        7

### Label Each cluster accordingly

In [28]:
labels = {
    0 : 'Bench Player',
    1 : 'Defensive Big Men',
    2 : '2-way Wing', 
    3 : 'Secondary floor general',
    4 : 'Elite Overall Center',
    5 : 'Shooting Specialist',
    6 : 'Defensive Specialist',
    7 : 'Elite Overall Guard'
}

In [29]:
df['cluster'] = df['cluster'].map(labels)

In [34]:
df.head(3)

         Player Pos  Age Team  Games  GS    MP   FG  FGA    FG%   3P  3PA    3P%   2P  2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  PTS  Year   PER    TS%   3PAr    FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  DBPM  BPM  VORP                  cluster
0   Carl Landry  PF   32  PHI     36  12  15.8  3.9  6.9  0.556  0.2  0.4  0.462  3.7  6.6  0.561  0.568  1.9  2.5  0.736  1.4  2.7  4.1  0.9  0.3  0.3  0.6  1.9  9.8  2016  22.4  0.605  0.052  0.364   9.1  19.2  14.0  11.1   1.0   1.2   7.1  24.0  1.8  0.3  2.1  0.176   2.6  -1.4  1.2   0.5               2-way Wing
1     O.J. Mayo  SG   28  MIL     41  24  26.6  2.9  7.8  0.371  1.3  4.0  0.321  1.6  3.9  0.421  0.452  0.8  1.0  0.775  0.3  2.2  2.6  2.9  1.2  0.2  1.8  3.1  7.8  2016   7.7  0.474  0.505  0.125   1.4   9.6   5.5  15.8   2.2   0.6  17.5  17.0 -0.7  0.6 -0.1 -0.005  -3.8  -0.2 -4.0  -0.6  Secondary floor general
2  Ray McCallum  PG   24  MEM     10   3  21.9  2.8  7.9  0.354  1.0  2.6  0.385  1.8  5.3  0.340  0.418  0.3  0.5  0.600  0.2  1.4  1.6  2.7  0.7  0.3  1.3  1.5  6.9  2016   9.1  0.449  0.288  0.103   1.9   9.3   5.6  18.5   1.3   1.2  13.6  16.8 -0.2  0.5  0.3  0.034  -2.6  -0.5 -3.1  -0.1             Bench Player

### Create a DF for each Cluster for EDA !

In [31]:
# cluster_0 = df.loc[df['cluster'] == 0, :].copy()

In [32]:
# pd.DataFrame(cluster_0)

Empty DataFrame
Columns: [Player, Pos, Age, Team, Games, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, Year, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, OWS, DWS, WS, WS/48, OBPM, DBPM, BPM, VORP, cluster]
Index: []

### Export Updated DF with Cluster labels to Tableau

In [33]:
df.to_csv('06-01-2020 cluster labels.csv')